#! /bin/sh

# Exit on error
set -e

# Function to show logo
pulsar_show_logo() {
    tput setaf 4
    echo "                                     "
    echo " ███████╗██╗██╗     ███████╗███████╗ "
    echo " ██╔════╝██║██║     ██╔════╝██╔════╝ "
    echo " █████╗  ██║██║     █████╗  ███████╗  PULSAR-MIME "
    echo " ██╔══╝  ██║██║     ██╔══╝  ╚════██║ "
    echo " ██║     ██║███████╗███████╗███████║ "
    echo " ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝ "
    echo "                                     "
    tput sgr0
}

# Load the default configs
. "$HOME/.config/pulsar/pulsar-configs/pulsar.conf"
. "$HOME/.config/pulsar/pulsar-configs/pulsar-mime.conf"

# Function to show help
pulsar_show_help() {

    # Show the logo in help
    pulsar_show_logo

    # Show to colored help
    RESET="$(tput sgr0)"
    BLUE="$(tput bold && tput setaf 4)"
    echo "${BLUE}pulsar-mime:${RESET} [-l, --mime-lists] [-d, --desktop-dirs directory] [-c, --config config_file] [-i, --icon icon]\n"

    # Exit after showing help
    exit 1
}

# Parse the user arguments
while [ $# -gt 0 ]; do

    case $1 in
        -c|--config) shift && . "$1";;
        -i|--icon) shift && PULSAR_ICON="$1";;
        -o|--open) shift && PULSAR_OPENER="$1";;
        -d|--desktop-dirs) shift && PULSAR_DIR="$1";;
        -l|--mime-lists) shift && PULSAR_MIME_LISTS="$1";;
        *) pulsar_show_help;;
    esac

    shift
done

# Prepend icon to list and show prompt
PULSAR_MIME="$( cat $PULSAR_MIME_LISTS | \
                sed "s|^|$PULSAR_ICON |" | \
                $PULSAR_PROMPT $PULSAR_PROMPT_OPTS )"

[ -z "$PULSAR_MIME" ] && exit 1

# Show desktop apps prompt
PULSAR_DESKTOP=$(find $PULSAR_DIR -name '*.desktop' $PULSAR_FIND_OPTS | \
                      sed "s|.*/||; s|\.desktop$||" | \
                      sort $PULSAR_SORT_OPTS | \
                      sed "s/^/$PULSAR_ICON /" | \
                      $PULSAR_PROMPT $PULSAR_OPENER_OPTS)

[ -z "$PULSAR_DESKTOP" ] && exit 1

# Remove the icon and the space
PULSAR_MIME=$(echo "$PULSAR_MIME" | sed "s/^$PULSAR_ICON //")
PULSAR_DESKTOP=$(echo "$PULSAR_DESKTOP" | sed "s/^$PULSAR_ICON //")

# Set the application for selected mime type
xdg-mime default $PULSAR_DESKTOP.desktop $PULSAR_MIME
