#! /bin/sh

# ██████╗ ██╗   ██╗██╗     ███████╗ █████╗ ██████╗
# ██╔══██╗██║   ██║██║     ██╔════╝██╔══██╗██╔══██╗
# ██████╔╝██║   ██║██║     ███████╗███████║██████╔╝
# ██╔═══╝ ██║   ██║██║     ╚════██║██╔══██║██╔══██╗
# ██║     ╚██████╔╝███████╗███████║██║  ██║██║  ██║
# ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

# Exit the script on error
set -e

# Function to show logo
pulsar_show_logo() {
    tput setaf 4
    echo "                              "
    echo " ██╗     ██╗███████╗████████╗ "
    echo " ██║     ██║██╔════╝╚══██╔══╝ "
    echo " ██║     ██║███████╗   ██║    PULSAR-LIST "
    echo " ██║     ██║╚════██║   ██║    "
    echo " ███████╗██║███████║   ██║    "
    echo " ╚══════╝╚═╝╚══════╝   ╚═╝    "
    echo "                              "
    tput sgr0
}

# Function to show help
pulsar_show_help() {

    # Show the logo in help
    pulsar_show_logo

    # Show to colored help
    RESET="$(tput sgr0)"
    BLUE="$(tput bold && tput setaf 4)"
    echo "${BLUE}pulsar-list:${RESET} [-o, --open opener] [-l, --list list_file] [-c, --config config_file] [-i, --icon icon]  [-r, --random-sort]\n"

    # Exit after showing help
    exit 1
}

# Show help if no comment
[ $# -eq 0 ] && pulsar_show_help

# Parse the user arguments
while [ $# -gt 0 ]; do

    case $1 in
        -c|--config) shift && . "$1";;
        -l|--list) shift && PULSAR_LIST="$1";;
        -i|--icon) shift && PULSAR_ICON="$1";;
        -o|--open) shift && PULSAR_OPENER="$1";;
        -r|--random-sort) PULSAR_SORT_OPTS="$PULSAR_SORT_OPTS --random-sort";;
        *) pulsar_show_help;;
    esac

    shift
done

# Change the current directory
cd "$PULSAR_DIR"

if [ "$PULSAR_SORT_ENABLE" = "false" ]; then
    # Prepend icon to list and show prompt (unsorted)
    PULSAR_ITEM="$( cat "$PULSAR_LIST" | \
                    sed "s|^|$PULSAR_ICON |" | \
                    $PULSAR_PROMPT $PULSAR_PROMPT_OPTS )"
else
    # Prepend icon to list and show prompt (sorted)
    PULSAR_ITEM="$( sort $PULSAR_SORT_OPTS "$PULSAR_LIST" | \
                    sed "s|^|$PULSAR_ICON |" | \
                    $PULSAR_PROMPT $PULSAR_PROMPT_OPTS )"
fi

[ -z "$PULSAR_ITEM" ] && exit 1

# Remove the icon, the space, and any :comment: from the selection
PULSAR_ITEM=$(echo "$PULSAR_ITEM" | \
                    sed "s/^$PULSAR_ICON //; s/:.*://g; s/  */ /g; s/^ //; s/ $//")

# Check if user is trying to add or remove the entry
case "$PULSAR_ITEM" in
    *">")
        PULSAR_CLEAN_ITEM="${PULSAR_ITEM%?}"

        # Add newline if file exists and is missing a trailing one
        if [ -s "$PULSAR_LIST" ] && [ "$(tail -c 1 "$PULSAR_LIST" | wc -l)" -eq 0 ]; then
            printf "\n" >> "$PULSAR_LIST"
        fi
        
        echo "$PULSAR_CLEAN_ITEM" >> "$PULSAR_LIST"
        exit 0
        ;;

    *"<")
        PULSAR_CLEAN_ITEM="${PULSAR_ITEM%?}"

        # Only attempt removal if the file exists and is not empty
        if [ -s "$PULSAR_LIST" ]; then
            # Create a temp file without the matching line
            grep -v -x "$PULSAR_CLEAN_ITEM" "$PULSAR_LIST" > "$PULSAR_LIST.tmp"
            
            # Replace the old list with the cleaned list
            mv "$PULSAR_LIST.tmp" "$PULSAR_LIST"
        fi
        exit 0
        ;;
esac

# Show the prompt for opener
if [ -z "$PULSAR_OPENER" ]; then

    PULSAR_OPENER="$( echo "$PULSAR_OPENERS $PULSAR_GLOBAL_OPENERS" | \
                            sed "s/^/$PULSAR_ICON /" | \
                            $PULSAR_PROMPT $PULSAR_OPENER_PROMPT_OPTS )"

    [ -z "$PULSAR_OPENER" ] && exit 1
fi

# Remove the icon and the space from the selection
PULSAR_OPENER=$(echo "$PULSAR_OPENER" | sed "s/^$PULSAR_ICON //")

# Run file using opener
if [ -z "$PULSAR_DETCH" ]; then
    $PULSAR_OPENER "$PULSAR_ITEM"
else
    $PULSAR_OPENER "$PULSAR_ITEM" &> /dev/null &
fi
