#! /bin/sh

#   ___   _   __  __ ___ ___
#  / __| /_\ |  \/  | __/ __|
# | (_ |/ _ \| |\/| | _|\__ \
#  \___/_/ \_\_|  |_|___|___/
#

pulsar-files -c ~/.config/pulsar/pulsar-configs/pulsar.conf \
             -c ~/.config/pulsar/pulsar-configs/pulsar-games.conf $@
