#! /bin/sh

# ██████╗ ██╗   ██╗██╗     ███████╗ █████╗ ██████╗
# ██╔══██╗██║   ██║██║     ██╔════╝██╔══██╗██╔══██╗
# ██████╔╝██║   ██║██║     ███████╗███████║██████╔╝
# ██╔═══╝ ██║   ██║██║     ╚════██║██╔══██║██╔══██╗
# ██║     ╚██████╔╝███████╗███████║██║  ██║██║  ██║
# ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

# Exit the script on error
set -e

# Function to show logo
pulsar_show_logo() {
    tput setaf 4
    "                                                            "
    " ███████╗██╗  ██╗███████╗ ██████╗██╗   ██╗████████╗███████╗ "
    " ██╔════╝╚██╗██╔╝██╔════╝██╔════╝██║   ██║╚══██╔══╝██╔════╝ "
    " █████╗   ╚███╔╝ █████╗  ██║     ██║   ██║   ██║   █████╗   PULSAR-EXECUTE "
    " ██╔══╝   ██╔██╗ ██╔══╝  ██║     ██║   ██║   ██║   ██╔══╝   "
    " ███████╗██╔╝ ██╗███████╗╚██████╗╚██████╔╝   ██║   ███████╗ "
    " ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝    ╚═╝   ╚══════╝ "
    "                                                            "
    tput sgr0
}

# Function to show help
pulsar_show_help() {

    # Show the logo in help
    pulsar_show_logo

    # Show to colored help
    RESET="$(tput sgr0)"
    BLUE="$(tput bold && tput setaf 4)"
    echo "${BLUE}pulsar-execute:${RESET} [-r, --run] [-p, --pause] [-c, --config config_file] [-i, --icon icon] [-r, --random-sort] [-o, --output-mode]\n"

    # Exit after showing help
    exit 1
}

# Load the default configs for script
. "$HOME/.config/pulsar/pulsar-configs/pulsar.conf"
. "$HOME/.config/pulsar/pulsar-configs/pulsar-execute.conf"

# Parse the user arguments
while [ $# -gt 0 ]; do

    case $1 in
        -r|--run) PULSAR_PAUSE="";;
        -c|--config) shift && . "$1";;
        -p|--pause) PULSAR_PAUSE="true";;
        -i|--icon) shift && PULSAR_ICON="$1";;
        -o|--output-mode) PULSAR_OUTPUT_MODE="true";;
        -r|--random-sort) PULSAR_SORT_OPTS="$PULSAR_SORT_OPTS --random-sort";;
        *) pulsar_show_help;;
    esac

    shift
done

# Show the prompt for commands
PULSAR_CMD="$( dmenu_path | sort $PULSAR_SORT_OPTS \
                          | sed "s/^/$PULSAR_ICON /" \
                          | $PULSAR_PROMPT $PULSAR_PROMPT_OPTS )"

[ -z "$PULSAR_CMD" ] && exit 1

# Remove the icon and the space from the selection
PULSAR_CMD=$(echo "$PULSAR_CMD" | sed "s/^$PULSAR_ICON //")

# Output command of desktop file
if [ "$PULSAR_OUTPUT_MODE" = "true" ]; then
    echo "$PULSAR_CMD"
    exit 0
fi

# Run file using opener
if [ -z "$PULSAR_DETCH" ]; then
    $PULSAR_CMD

else
    if [ -z "$PULSAR_PAUSE" ]; then
    
        # Normally run command (without pause)
        $PULSAR_CMD &> /dev/null &

    elif [ "$PULSAR_PAUSE" = "false" ]; then

        # Run command using shell in terminal (without pause)
        $PULSAR_TERM sh -c "$PULSAR_CMD" &> /dev/null &

    elif [ "$PULSAR_PAUSE" = "true" ]; then

        # Run command using shell in terminal (with pause)
        $PULSAR_TERM sh -c "echo '$ ' $PULSAR_CMD; \
                                      $PULSAR_CMD; read -p ':' PROMPT" &> /dev/null &
    fi
fi
