#! /bin/sh

# ██████╗ ██╗   ██╗██╗     ███████╗ █████╗ ██████╗ 
# ██╔══██╗██║   ██║██║     ██╔════╝██╔══██╗██╔══██╗
# ██████╔╝██║   ██║██║     ███████╗███████║██████╔╝
# ██╔═══╝ ██║   ██║██║     ╚════██║██╔══██║██╔══██╗
# ██║     ╚██████╔╝███████╗███████║██║  ██║██║  ██║
# ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝

# Exit the script on error
set -e

# Function to show logo
pulsar_show_logo() {
    tput setaf 4
    echo "                               "
    echo " ███╗   ███╗ █████╗ ███╗   ██╗ "
    echo " ████╗ ████║██╔══██╗████╗  ██║ "
    echo " ██╔████╔██║███████║██╔██╗ ██║  PULSAR-MANPAGES"
    echo " ██║╚██╔╝██║██╔══██║██║╚██╗██║ "
    echo " ██║ ╚═╝ ██║██║  ██║██║ ╚████║ "
    echo " ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ "
    echo "                               "
    tput sgr0
}

# Function to show help
pulsar_show_help() {

    # Show the logo in help
    pulsar_show_logo

    # Show to colored help
    RESET="$(tput sgr0)"
    BLUE="$(tput bold && tput setaf 4)"
    echo "${BLUE}pulsar-manpages:${RESET} [-d, --detailed] [-s, --simple] [-m, --manpager] [-c, --config config_file] [-i, --icon icon] [-r, --random-sort]\n"

    # Exit after showing help
    exit 1
}

# Load the default configs for script
. "$HOME/.config/pulsar/pulsar-configs/pulsar.conf"
. "$HOME/.config/pulsar/pulsar-configs/pulsar-manpages.conf"

# Parse the user arguments
while [ $# -gt 0 ]; do

    case $1 in
        -c|--config) shift && . "$1";;
        -s|--simple) PULSAR_VIEW="simple";;
        -i|--icon) shift && PULSAR_ICON="$1";;
        -d|--detailed) PULSAR_VIEW="detailed";;
        -m|--manpager) shift && PULSAR_MANPAGER="$1";;
        -r|--random-sort) PULSAR_SORT_OPTS="$PULSAR_SORT_OPTS --random-sort";;
        *) pulsar_show_help;;
    esac

    shift
done

if [ "$PULSAR_VIEW" = "detailed" ]; then

    # Show prompt for detailed manpage view
    PULSAR_MANPAGE="$( apropos . $PULSAR_APROPOS_OPTS | sort $PULSAR_SORT_OPTS \
                                                      | sed "s/^/$PULSAR_ICON /" \
                                                      | $PULSAR_PROMPT $PULSAR_PROMPT_OPTS \
                                                      | sed "s/^$PULSAR_ICON //" | tr -d '()' \
                                                      | awk -F" " '{print $2" "$1}' )"

elif [ "$PULSAR_VIEW" = "simple" ]; then

    # Show prompt for simple manpage view
    PULSAR_MANPAGE="$( apropos . $PULSAR_APROPOS_OPTS | sort $PULSAR_SORT_OPTS \
                                                      | awk -F" " '{print $1" "$2}' \
                                                      | sed "s/^/$PULSAR_ICON /" \
                                                      | $PULSAR_PROMPT $PULSAR_PROMPT_OPTS \
                                                      | sed "s/^$PULSAR_ICON //" | tr -d '()' \
                                                      | awk -F" " '{print $2" "$1}' )"
fi

[ -z "$PULSAR_MANPAGE" ] && exit 1

# Open manpage in pager
if [ -z "$PULSAR_DETCH" ]; then
    $PULSAR_MANPAGER $PULSAR_MANPAGE
else
    $PULSAR_TERM sh -c "$PULSAR_MANPAGER \
                        $PULSAR_MANPAGE" &> /dev/null &
fi
