#! /bin/sh

# ██╗  ██╗ ██████╗██╗     ██╗██████╗ 
# ╚██╗██╔╝██╔════╝██║     ██║██╔══██╗
#  ╚███╔╝ ██║     ██║     ██║██████╔╝
#  ██╔██╗ ██║     ██║     ██║██╔═══╝ 
# ██╔╝ ██╗╚██████╗███████╗██║██║     
# ╚═╝  ╚═╝ ╚═════╝╚══════╝╚═╝╚═╝     

echo "$@" | xclip -selection primary
echo "$@" | xclip -selection secondary
echo "$@" | xclip -selection clipboard