#! /bin/sh

# ███╗   ███╗██╗███╗   ███╗███████╗
# ████╗ ████║██║████╗ ████║██╔════╝
# ██╔████╔██║██║██╔████╔██║█████╗  
# ██║╚██╔╝██║██║██║╚██╔╝██║██╔══╝  
# ██║ ╚═╝ ██║██║██║ ╚═╝ ██║███████╗
# ╚═╝     ╚═╝╚═╝╚═╝     ╚═╝╚══════╝

pulsar-mime -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
            -c ~/.config/pulsar/tpulsar-configs/tpulsar-mime.conf $@
