#! /bin/sh

# ███████╗██╗██╗     ███████╗
# ██╔════╝██║██║     ██╔════╝
# █████╗  ██║██║     █████╗  
# ██╔══╝  ██║██║     ██╔══╝  
# ██║     ██║███████╗███████╗
# ╚═╝     ╚═╝╚══════╝╚══════╝

pulsar-filebookmarks -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                     -c ~/.config/pulsar/tpulsar-configs/tpulsar-filebookmarks.conf $@