#! /bin/sh

# ███████╗███╗   ███╗ ██████╗      ██╗██╗
# ██╔════╝████╗ ████║██╔═══██╗     ██║██║
# █████╗  ██╔████╔██║██║   ██║     ██║██║
# ██╔══╝  ██║╚██╔╝██║██║   ██║██   ██║██║
# ███████╗██║ ╚═╝ ██║╚██████╔╝╚█████╔╝██║
# ╚══════╝╚═╝     ╚═╝ ╚═════╝  ╚════╝ ╚═╝

pulsar-emojis -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
              -c ~/.config/pulsar/tpulsar-configs/tpulsar-emojis.conf $@
