#! /bin/sh

# ███████╗██╗  ██╗███████╗ ██████╗
# ██╔════╝╚██╗██╔╝██╔════╝██╔════╝
# █████╗   ╚███╔╝ █████╗  ██║     
# ██╔══╝   ██╔██╗ ██╔══╝  ██║     
# ███████╗██╔╝ ██╗███████╗╚██████╗
# ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝

pulsar-execute -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
               -c ~/.config/pulsar/tpulsar-configs/tpulsar-execute.conf $@