#! /bin/sh

#  ██████╗███╗   ███╗██████╗ 
# ██╔════╝████╗ ████║██╔══██╗
# ██║     ██╔████╔██║██║  ██║
# ██║     ██║╚██╔╝██║██║  ██║
# ╚██████╗██║ ╚═╝ ██║██████╔╝
#  ╚═════╝╚═╝     ╚═╝╚═════╝ 

pulsar-cmdbookmarks -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                    -c ~/.config/pulsar/tpulsar-configs/tpulsar-cmdbookmarks.conf $@