#! /bin/sh

# ███╗   ███╗ █████╗ ███╗   ██╗
# ████╗ ████║██╔══██╗████╗  ██║
# ██╔████╔██║███████║██╔██╗ ██║
# ██║╚██╔╝██║██╔══██║██║╚██╗██║
# ██║ ╚═╝ ██║██║  ██║██║ ╚████║
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝

pulsar-process -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
               -c ~/.config/pulsar/tpulsar-configs/tpulsar-process.conf $@
