#! /bin/sh

#   ___   _   __  __ ___ ___
#  / __| /_\ |  \/  | __/ __|
# | (_ |/ _ \| |\/| | _|\__ \
#  \___/_/ \_\_|  |_|___|___/
#

pulsar-games -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
             -c ~/.config/pulsar/tpulsar-configs/tpulsar-games.conf $@