#! /bin/sh

# ██████╗  █████╗  ██████╗██╗  ██╗
# ██╔══██╗██╔══██╗██╔════╝██║ ██╔╝
# ██████╔╝███████║██║     █████╔╝ 
# ██╔═══╝ ██╔══██║██║     ██╔═██╗ 
# ██║     ██║  ██║╚██████╗██║  ██╗
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝

pulsar-packages -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                -c ~/.config/pulsar/tpulsar-configs/tpulsar-packages.conf $@